### ISSUE TITLE
Performance analysis

### ISSUE THREAD

**Issue by hauke96** [hauke96/wiki2book#13]
Take a look at the integration tests. Converting the German "Erde" article with already downloaded files takes already 5.5 seconds, converting the "Sonne" article 2.3 seconds. That's too slow.

Profiling code already exists as comments in the `main.go` file.

### Tasks of this issue are

* [x] Analysis of slow code parts
* [x] Propose solutions to increase performance
* [x] Create separate issues for performance enhancements

### Findings

1. Regex and string replacements are still (as of 2023-11 / 94f009bcae671cdab0571f8fe29713474b697fd0 ) a problem. Regex usage account for ~25% of the time and string replacements for ~15%.
2. Using caching (and e.g. not processing already processed images) had a HUGE effect! See analysis below.
3. Reading cached article files is unnecessary. Instead, the mapping from "filename in article text" to "filename on disk" should be stored and used.
4. Garbage collection adds a significant amount of time. This makes about an extra 20-30% of the general processing time (without generating the EPUB file).

A generated profiling call-graph can be seen here (as of 94f009bcae671cdab0571f8fe29713474b697fd0): [profile.pdf](https://github.com/hauke96/wiki2book/files/13400171/profile007.pdf)

#### Image caching optimization

Performance analysis of the optimization made in 442b663aa0b312795e5b1522d797680044cce5f7. Each entry is the average over three runs.

| Task | pre optimization | after optimization | speedup |
| -- | -- | -- | -- |
| project de/Astronomie | 116,348 | 0,956 | 121,62 |
| article de/Erde | 3,054 | 0,0396 | 76,99 |
| tests.sh | 11,697 | 6,9976 | 1,67 |
